jwt:
  secret: test-secret
server:
  port: 8080
  servlet:
    context-path: /todo1-kardex/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 38c2be9743125c93bfe4372fdd0e79f3a80f4ebaf6ce20281c2ddafd4deb7a9f
    url: jdbc:postgresql://ec2-44-195-16-34.compute-1.amazonaws.com:5432/d87ao5q3h5qt2f
    username: nmyvwdjjzegcnc
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs